apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: mlb-ai-api-gateway
  namespace: mlb-ai-go
  labels:
    app.kubernetes.io/name: mlb-ai-api-gateway
    app.kubernetes.io/part-of: mlb-ai-go
spec:
  gatewayClassName: approuting-istio
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
