namespace MlbAi.Application.Models;

public sealed record MlbGameDto(
    string GamePk,
    DateOnly GameDate,
    DateTimeOffset? GameTimeUtc,
    int? AwayTeamId,
    string AwayTeam,
    int? HomeTeamId,
    string HomeTeam,
    string Status,
    int? AwayScore = null,
    int? HomeScore = null,
    string? AwayRecord = null,
    string? HomeRecord = null,
    string? AwayProbablePitcher = null,
    string? HomeProbablePitcher = null,
    bool? AwayWinner = null,
    bool? HomeWinner = null,
    int? VenueId = null,
    string? VenueName = null,
    string? GameType = null,
    string? DayNight = null,
    int? ScheduledInnings = null,
    int? GamesInSeries = null,
    int? SeriesGameNumber = null,
    string? SeriesDescription = null,
    string? DoubleHeader = null,
    int? CurrentInning = null,
    string? CurrentInningOrdinal = null,
    string? InningHalf = null,
    int? Balls = null,
    int? Strikes = null,
    int? Outs = null,
    int? AwayHits = null,
    int? AwayErrors = null,
    int? HomeHits = null,
    int? HomeErrors = null);
