apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mlb-ai-api-tls
  namespace: mlb-ai-go
  labels:
    app.kubernetes.io/name: mlb-ai-api
    app.kubernetes.io/part-of: mlb-ai-go
spec:
  secretName: mlb-ai-api-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - 20-24-106-104.sslip.io
