apiVersion: v1
kind: Secret
metadata:
  name: mlb-ai-api-secrets
  namespace: mlb-ai-go
  labels:
    app.kubernetes.io/name: mlb-ai-api
    app.kubernetes.io/part-of: mlb-ai-go
type: Opaque
stringData:
  APPLICATIONINSIGHTS_CONNECTION_STRING: "<application-insights-connection-string>"
  ApplicationInsights__ConnectionString: "<application-insights-connection-string>"
